### ISSUE TITLE
ValueError: np_data = np.frombuffer(b, dt)

### ISSUE THREAD

**Issue by elaOnMars** [maierman/binbuffer#1]
Hi,

tryied to work through your tutorial. But I receive an error and don't know how to fix this:

with open('./simple_binary.bin', 'rb') as f:
    b = f.read()                 # read in the binary file as bytes
    
np_data = np.frombuffer(b, dt)   # creates a NumPy array
df = pd.DataFrame(np_data)
df

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-82-729fe0bde6d8> in <module>
      3     b = f.read()                 # read in the binary file as bytes
      4 
----> 5 np_data = np.frombuffer(b, dt)   # creates a NumPy array
      6 df = pd.DataFrame(np_data)
      7 df

ValueError: buffer size must be a multiple of element size

**Comment by maierman** [comment]
This error means that the number of bytes in the bytes object 'b' is not a multiple of the size of the numpy dtype 'dt'.  You can view these with:  `len(b)` and `dt.itemsize` On my machine these are 39 and 13.  Did dt maybe get redefined differently in your session?  Try running the notebook again in a clean session and if the issue persists reopen the issue and let me know what you get for dt.itemsize and len(b) and what system you're running the notebook on.
